using LocadoraDeVeiculos.Aplicacao.ModuloFuncionario.Commands.SelecionarTodos;

namespace LocadoraDeVeiculos.Aplicacao.ModuloFuncionario.Commands.SelecionarPorId;

public record SelecionarFuncionarioPorIdResponse(SelecionarFuncionariosDto Funcionario);
