using LocadoraDeVeiculos.Aplicacao.ModuloCondutor.Commands.SelecionarTodos;

namespace LocadoraDeVeiculos.Aplicacao.ModuloCondutor.Commands.SelecionarPorId;

public record SelecionarCondutorPorIdResponse(SelecionarCondutoresDto Condutor);
