using LocadoraDeVeiculos.Aplicacao.ModuloAluguel.Commands.SelecionarTodos;

namespace LocadoraDeVeiculos.Aplicacao.ModuloAluguel.Commands.SelecionarPorId;

public record SelecionarAluguelPorIdResponse(SelecionarAluguelDto Aluguel);
